"""empty message

Revision ID: ea1adeb0b6a2
Revises: 7e42bdc9bbe8
Create Date: 2024-05-12 22:20:41.920376

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea1adeb0b6a2'
down_revision: Union[str, None] = '7e42bdc9bbe8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
